language: python

# you can use Python 3.7 instead
python: "3.8.3"

# Install any dependencies
install:
  - pip install -r requirements.txt
    
# script to run tests. Script can have many commands, one per line.
script: 
  - coverage run manage.py test

