"""Migrations are how Django stores changes to your models."""
# Generated by Django 3.1 on 2020-09-16 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """The changes of web server but have option end date."""

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end dated'),
            preserve_default=False,
        ),
    ]
